
##### RESOURCES #####
mem: '16000'
threads: 8 # used to parallelize download, FASTQ to gzip conversion and FASTQ to BAM conversion

##### GENERAL #####
project_name: PublicDataProject # name of the project/dataset
result_path: results/ # path to the output folder

# Flag to download and merge only the metadata of all accessions
metadata_only: 0 # options: 0=no; 1=yes

# define output format of data files as fastq.gz or unmapped/unaligned/raw bam files
output_format: bam # options: "bam" or "fastq"

# Supported accession ids to dwnload (see: https://github.com/BioOmics/iSeq)
accession_ids:
    - GSE122139 # BioProject
    - SAMC017083 # BioSample
    - ERS5684710 # Sample
    - CRX020217 # Experiment
    - SRS2024210 # Run
